version: '3.7'

services:
  app:
    container_name: app
    build:
      context: .
      target: node
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: .env
    networks:
      - app-network

  database:
    image: postgres
    container_name: time_tracker_database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    networks:
      - app-network

volumes:
  pgdata:
    driver: local
networks:
  app-network:
    driver: bridge